export const forbiddenTravelAreas = ["Abkhazia", "South Ossetia"] as const;

export const bookingStatuses = [
  "pending",
  "pre_approved",
  "awaiting_payment",
  "confirmed",
  "rejected",
  "cancelled",
  "completed",
] as const;

export type BookingStatus = (typeof bookingStatuses)[number];

export const blockingBookingStatuses = [
  "pre_approved",
  "awaiting_payment",
  "confirmed",
] as const satisfies readonly BookingStatus[];

export const defaultCar = {
  make: "Volkswagen",
  model: "Passat",
  year: 2013,
  engine: "2.5",
  transmission: "Automatic",
  fuel: "Petrol + LPG",
  seats: 5,
  bodyType: "Sedan",
  luggageCapacity: "3 suitcases",
  location: "Batumi, Georgia",
  active: true,
} as const;

export const defaultSettings = {
  ownerName: "Owner",
  ownerEmail: "owner@example.com",
  ownerWhatsappNumber: "+995555000000",
  ownerTelegramUsername: "batumi_car_rental",
  primaryCurrency: "GEL",
  showUsdEquivalent: false,
  usdGelExchangeRate: null,
  minimumDriverAge: 21,
  minimumDrivingExperienceYears: 2,
  depositAmountGel: 300,
  insuranceIncluded: true,
  insuranceSummary:
    "Insurance details are confirmed before final approval. Damage, fines, missing fuel, smoking, off-road use, beach driving, and unreported accidents may be charged separately.",
  insuranceExcessGel: null,
  mileagePolicy:
    "Unlimited mileage for rentals of 2+ days. One-day rentals include 200 km, then 0.50 GEL per extra km.",
  oneDayKmLimit: 200,
  extraKmPriceGel: 0.5,
  nightSurchargeGel: 30,
  nightSurchargeStartHour: 22,
  nightSurchargeEndHour: 8,
  cityDeliveryFeeGel: 0,
  airportDeliveryFeeGel: 0,
  termsVersion: "v1",
  privacyVersion: "v1",
} as const;

export const defaultPricingRules = [
  {
    seasonName: "low",
    startMonth: 11,
    startDay: 1,
    endMonth: 3,
    endDay: 31,
    minDays: 1,
    maxDays: 1,
    dailyPriceGel: 110,
  },
  {
    seasonName: "low",
    startMonth: 11,
    startDay: 1,
    endMonth: 3,
    endDay: 31,
    minDays: 2,
    maxDays: 3,
    dailyPriceGel: 100,
  },
  {
    seasonName: "low",
    startMonth: 11,
    startDay: 1,
    endMonth: 3,
    endDay: 31,
    minDays: 4,
    maxDays: 7,
    dailyPriceGel: 90,
  },
  {
    seasonName: "low",
    startMonth: 11,
    startDay: 1,
    endMonth: 3,
    endDay: 31,
    minDays: 8,
    maxDays: 15,
    dailyPriceGel: 80,
  },
  {
    seasonName: "low",
    startMonth: 11,
    startDay: 1,
    endMonth: 3,
    endDay: 31,
    minDays: 16,
    maxDays: 30,
    dailyPriceGel: 70,
  },
  {
    seasonName: "shoulder",
    startMonth: 4,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    minDays: 1,
    maxDays: 1,
    dailyPriceGel: 125,
  },
  {
    seasonName: "shoulder",
    startMonth: 4,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    minDays: 2,
    maxDays: 3,
    dailyPriceGel: 115,
  },
  {
    seasonName: "shoulder",
    startMonth: 4,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    minDays: 4,
    maxDays: 7,
    dailyPriceGel: 105,
  },
  {
    seasonName: "shoulder",
    startMonth: 4,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    minDays: 8,
    maxDays: 15,
    dailyPriceGel: 95,
  },
  {
    seasonName: "shoulder",
    startMonth: 4,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    minDays: 16,
    maxDays: 30,
    dailyPriceGel: 85,
  },
  {
    seasonName: "shoulder",
    startMonth: 9,
    startDay: 1,
    endMonth: 10,
    endDay: 31,
    minDays: 1,
    maxDays: 1,
    dailyPriceGel: 125,
  },
  {
    seasonName: "shoulder",
    startMonth: 9,
    startDay: 1,
    endMonth: 10,
    endDay: 31,
    minDays: 2,
    maxDays: 3,
    dailyPriceGel: 115,
  },
  {
    seasonName: "shoulder",
    startMonth: 9,
    startDay: 1,
    endMonth: 10,
    endDay: 31,
    minDays: 4,
    maxDays: 7,
    dailyPriceGel: 105,
  },
  {
    seasonName: "shoulder",
    startMonth: 9,
    startDay: 1,
    endMonth: 10,
    endDay: 31,
    minDays: 8,
    maxDays: 15,
    dailyPriceGel: 95,
  },
  {
    seasonName: "shoulder",
    startMonth: 9,
    startDay: 1,
    endMonth: 10,
    endDay: 31,
    minDays: 16,
    maxDays: 30,
    dailyPriceGel: 85,
  },
  {
    seasonName: "high",
    startMonth: 7,
    startDay: 1,
    endMonth: 8,
    endDay: 31,
    minDays: 1,
    maxDays: 1,
    dailyPriceGel: 150,
  },
  {
    seasonName: "high",
    startMonth: 7,
    startDay: 1,
    endMonth: 8,
    endDay: 31,
    minDays: 2,
    maxDays: 3,
    dailyPriceGel: 140,
  },
  {
    seasonName: "high",
    startMonth: 7,
    startDay: 1,
    endMonth: 8,
    endDay: 31,
    minDays: 4,
    maxDays: 7,
    dailyPriceGel: 125,
  },
  {
    seasonName: "high",
    startMonth: 7,
    startDay: 1,
    endMonth: 8,
    endDay: 31,
    minDays: 8,
    maxDays: 15,
    dailyPriceGel: 110,
  },
  {
    seasonName: "high",
    startMonth: 7,
    startDay: 1,
    endMonth: 8,
    endDay: 31,
    minDays: 16,
    maxDays: 30,
    dailyPriceGel: 95,
  },
] as const;
